#!/bin/bash

show_usage()
{
  cat<<EOF >&2
Usage: $0 [OPTIONS] -f SOURCE -t TARGET

Available options:
  -f PATH  copy data from PATH (e.g. /media/cdrom)
  -t PATH  copy data to PATH (e.g. /usr/local/share/syndre)

  -M       do not copy music
  -l LANG  choose language LANG

  -h       print usage information

Available languages: ${LANGS}
EOF
}

if [ $# -eq 1 -a "x$1" = "x--help" ]; then
  show_usage
  exit 0
fi

OWN_TARGET="no"
SOURCE=""
TARGET=""
LANGS="eng fre ger ita spa swe"
LANG="eng"

GFX_VERSION="0.0.1.14"
GFX_PACKAGE="syndicatfx-gfx-0_0_1_14"
GFX_PKG_MD5="20bfa8bdecf691e43e3acf4246622e3c"

SFX_VERSION="0.1.0.7"
SFX_PACKAGE="syndicatfx-sfx-0_1_0_7"
SFX_PKG_MD5="e691526436910cb4e4bed7e65480ebd1"

OPTS="f:t:l:h"

while getopts "$OPTS" arg; do
  case "$arg" in
    f)
      SOURCE="$OPTARG"
      ;;
    t)
      TARGET="$OPTARG"
      ;;
    l)
      LANG="$OPTARG"
      ;;
    h)
      show_usage
      exit 0
      ;;
    *)
      exit 1
  esac
done

check_source()
{
  if [ -z "$SOURCE" ]; then
    echo "Source not specified.  Try --help." >&2
    exit 1
  fi
  if ! [ -d "$SOURCE" ]; then
    echo "Source directory '$SOURCE' does not exist!" >&2
    return 1
  fi

  if [ -d "$SOURCE/game" ]; then
    SOURCE="$SOURCE/game"
    return 0
  fi

  echo "Source directory '$SOURCE' does not contain the data from the game!" >&2
  return 1
}

check_target()
{
  if [ -z "$TARGET" ]; then
    echo "Target not specified.  Try --help." >&2
    exit 1
  fi

  if [ -d "$TARGET" ]; then
    local file_count=`ls "$TARGET" | wc -l | sed 's/[^0-9]//g'` || return 1

    if [ "x$file_count" != "x0" ]; then
      echo "Target directory '$TARGET' is not empty!" >&2
      return 1
    fi
  fi

  install -v -d "$TARGET" || return 1
  OWN_TARGET="yes"

  return 0
}

dl_package()
{
  local proj_nam=$1
  local pkg_nam=$2
  local pkg_ver=$3
  local pkg_md5=$4

  local real_md5=`md5sum "${pkg_nam}.zip" | cut -d " " -f1`
  if [[ "x${real_md5}" != "x${pkg_md5}" ]]; then
    wget "https://github.com/${proj_nam}/releases/download/${pkg_ver}/${pkg_nam}.zip" || return 1
  fi

  local real_md5=`md5sum "${pkg_nam}.zip" | cut -d " " -f1`
  if [[ "x${real_md5}" != "x${pkg_md5}" ]]; then
    printf 'Downloaded package MD5 mismatch: %s\n' "$pkg_nam" >&2
    printf 'Expected md5sum: %s\n' "$pkg_md5" >&2
    return 1
  fi

  return 0
}

download_packages()
{
  dl_package "swfans/syndicatfx-gfx" "${GFX_PACKAGE}" "${GFX_VERSION}" "${GFX_PKG_MD5}" || return 1
  dl_package "swfans/syndicatfx-sfx" "${SFX_PACKAGE}" "${SFX_VERSION}" "${SFX_PKG_MD5}" || return 1

  return 0
}

install_file()
{
  local fname="$1"

  # Find the input file name ignoring case
  local src=`find "$SOURCE" -ipath "$SOURCE/$fname"`
  local dst="$TARGET/$fname"

  if [ ! -n "$src" ]; then
    printf 'File missing from your SOURCE: %s\n' "$fname" >&2
    return 1
  fi

  install -v -T -m 0644 "$src" "$dst" || return 1

  return 0
}

install_file_to()
{
  local fname="$1"
  local dstdir="$2"

  # Find the input file name ignoring case
  local src=`find "$SOURCE" -ipath "$SOURCE/$fname"`
  local fbase=`basename "$fname"`
  local dst="$TARGET/$dstdir/$fbase"

  if [ ! -n "$src" ]; then
    printf 'File missing from your SOURCE: %s\n' "$fname" >&2
    return 1
  fi

  install -v -T -m 0644 "$src" "$dst" || return 1

  return 0
}

install_dir()
{
  local dname="$1"

  local dst="$TARGET/$dname"

  install -v -d "$dst" || return 1

  return 0
}

copy_data()
{
  install_dir "data" || return 1

  for fn in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 90 91 92 93 94 95 96 97 98 99; do
    install_file "data/game${fn}.dat" || return 1
  done

  for fn in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 17 18 19 20 21 31 32 34 35 37 38 39 40 41 43 50 51 52 53 54 55 56 57 58 60 61 62 63 64 65 66 67 70 71 72 73 80 81 82 90 91 92 93 94; do
    install_file "data/map${fn}.dat" || return 1
  done

  for fn in  01  02  03  04  05  06  07  08  09  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50; do
    install_file "data/miss${fn}.dat" || return 1
  done

  for fn in 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150; do
    install_file "data/miss${fn}.dat" || return 1
  done

  for fn in 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250; do
    install_file "data/miss${fn}.dat" || return 1
  done

  for fn in 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350; do
    install_file "data/miss${fn}.dat" || return 1
  done

  for fn in 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450; do
    install_file "data/miss${fn}.dat" || return 1
  done

  for fn in hpointer hspr-0 hspr-1; do
    install_file "data/${fn}.dat" || return 1
    install_file "data/${fn}.tab" || return 1
  done

  for fn in mfnt-0; do
    install_file "data/${fn}.dat" || return 1
    install_file "data/${fn}.tab" || return 1
  done

  for fn in hpal01 hpal02 hpal03 hpal04 hpal05 hpalette; do
    install_file "data/${fn}.dat" || return 1
  done

  for fn in intro.dat intro.xmi; do
    install_file "data/${fn}" || return 1
  done

  for fn in isnds-0 isnds-1; do
    install_file "data/${fn}.dat" || return 1
    install_file "data/${fn}.tab" || return 1
  done

  for fn in gsound-0 sound-0 sound-1 ; do
    install_file "data/${fn}.dat" || return 1
    install_file "data/${fn}.tab" || return 1
  done

  for fn in sample.ad sample.opl syngame.xmi gamedg.dll gamefm.dll; do
    install_file "data/${fn}" || return 1
  done

  for fn in col01.dat hblk01.dat hele-0.ani hfnt01.dat hfra-0.ani hreq.dat hsta-0.ani mselect.pal; do
    install_file "data/${fn}" || return 1
  done

  for fn in mbrief mbrieout mconfout mconfup mconscr mdebrief mdeout mendlose mendwin mgamewin mlogos mlosa mlosaout mlosegam mmap mmapblk mmapout mminlogo mmulti mmultout moption moptout mresout mresrch mscrenup mselect mselout mtitle; do
    install_file "data/${fn}.dat" || return 1
  done

  install_dir "sound" || return 1

  return 0
}

extract_packages()
{
  unzip -o "${GFX_PACKAGE}.zip" -d "${TARGET}" || return 1
  find "$TARGET/syndre/data" -mindepth 1 -maxdepth 1 -type f -iname '*.*' \
    | while read file; do
        mv -vn "$file" -t "${TARGET}/data" || return 1
      done
  for dirn in $(echo ${LANGS}); do
    find "$TARGET/syndre/language/${dirn}" -mindepth 1 -maxdepth 1 -type f -iname '*.*' \
      | while read file; do
          mv -vn "$file" -t "${TARGET}/language/${dirn}" || return 1
        done
  done
  rm -rf "${TARGET}/syndre" || return 1

  unzip -o "${SFX_PACKAGE}.zip" -d "${TARGET}" || return 1
  find "$TARGET/syndre/sound" -mindepth 1 -maxdepth 1 -type f -iname '*.dat' \
    | while read file; do
        mv -vn "$file" -t "${TARGET}/sound" || return 1
      done
  rm -rf "${TARGET}/syndre" || return 1

  return 0
}

check_language()
{
  case "$LANG" in
    eng)
      LANG_NAME="English"
      LANG_NUM=0
      ;;
    fre)
      LANG_NAME="French"
      LANG_NUM=1
      ;;
    ger)
      LANG_NAME="German"
      LANG_NUM=0
      ;;
    ita)
      LANG_NAME="Italian"
      LANG_NUM=2
      ;;
    spa)
      LANG_NAME="Spanish"
      LANG_NUM=0
      ;;
    swe)
      LANG_NAME="Swedish"
      LANG_NUM=0
      ;;
    *)
      echo "Unsupported language: $LANG." >&2
      return 1
      ;;
  esac
  return 0
}

create_run_script()
{
  cat<<EOF >"$TARGET/run.sh"
#!/bin/sh
./syndre -c ${LANG_NUM}
EOF
  [ $? -eq 0 ] || return 1
  return 0
}

error()
{
  if [ "$OWN_TARGET" = "yes" ]; then
    echo "Removing target directory."
    rm -rf "$TARGET"
  fi
  echo "Failed to install data (consult the above error messages)."
  exit 1
}

check_source || error
check_language || error
check_target || error
download_packages || error
copy_data || error
extract_packages || error
create_run_script || error

echo "Data successfully installed."
